### ISSUE TITLE
Явно показывать ошибки валидации кода сниппетов

### ISSUE THREAD

**Issue by nicksp** [jsbench/jsbench.github.io#14]
Сделать так, чтобы пользователи сервиса смогли видеть явные ошибки в коде своих сниппетов, если таковые имеются. Сейчас некоторые синтаксические ошибки отображаются в консоли во время исполнения теста сниппета, что не очень прозрачно для пользователей. А было бы здорово видеть, что с нашим кодом что-то не так.

Например, следующий код выплюнет `Uncaught SyntaxError: Unexpected identifier` в консоль, но не пользователю:

``` javascript
b = {
    a: 2
    b: 3
}
```

**Comment by RubaXa** [comment]
:+1:  вот прямо сейчас страдал. Для Ace есть плагины по валидации JS, нужно их подключить (на память не помню, надо гуглить)

**Comment by nicksp** [comment]
Сегодня посмотрю. Найду - реализуем.
