### ISSUE TITLE
Полировка UX

### ISSUE THREAD

**Issue by nicksp** [jsbench/jsbench.github.io#15]
Выполнить следующие пункты для более интуитивного и непробиваемого UI **(список продолжать по мере нахождения улучшения)**:
- [x] Задизейблить кнопки `Run`, когда нет ни одного сниппета
- [x] Запретить удаление сниппетов во время фактического тестирования во избежание `Uncaught TypeError: Cannot set property 'innerHTML' of undefined`
- [x] Не запускать тест для пустых сниппетов
- [x] Когда присутствуют результаты тестов, и мы удаляем все сниппеты, а потом добавляем один - страница прыгает. Добавить `overflow-y: scroll` для `htm`
- [ ] Перед каждым новым бенчмарком, очищать график рельтатов во избежание неприятных моментов с правильной его отрисовкой (например, когда удалили один тест и запустили заново, учитывая что тест прогоняется только для непустых сниппетов, а не для всех как сейчас). Это приводит в ошибкам типа: `Uncaught Error: Row {0} has {NUM} columns, but must have {NUM-1}`

**P.S.** C графиками пока неоднозначно как поступить. Пока оставил. Может после тестирования, пришлёшь свои замечания, правки, комменты...

**Comment by nicksp** [comment]
Взял в разработку эту таску.

**Comment by RubaXa** [comment]
По поводу  третьего пункта, самым простым и верным решением будет перекрыть все снипеты div `opacity: 0.1`. Ещё это убережет от срабатывания события Ace, которые могу влиять на результаты прогона.

**Comment by nicksp** [comment]
Перекрыть в какой момент?

**Comment by RubaXa** [comment]
Перед запуском тестов закрываем всё прозрачным `div`, по завершению скрываем, я так постоянно делаю, когда нужно лочить интерфейс, дешево и сердито ;]

**Comment by nicksp** [comment]
Аа.. понял тебя. Сделаю.
