### ISSUE TITLE
Лицензия

### ISSUE THREAD

**Issue by finom** [jsbench/jsbench.github.io#20]
Под какой лицензией проект распространяется? Форкнуть то я форкну, но как я могу этим пользоваться, не понятно.

**Comment by RubaXa** [comment]
Так MIT: https://github.com/jsbench/jsbench.github.io/blob/dev/package.json#L9

**Comment by finom** [comment]
@RubaXa упс, не подумал в пакейдж заглянуть. Обычно в опенсорцных проектах есть license.md.

**Comment by RubaXa** [comment]
Когда как, да. У меня философия простая, всё что выложено в паблик, принадлежит всем.

**Comment by finom** [comment]
@RubaXa принадлежит то всем, но как распространять - вопрос. CC Attribution требует указания автора, GPL - выкладывать все свои наработки под такой же лицензией и пр.

**Comment by nicksp** [comment]
Уже закрыто, но всё таки :) 
Сегодня как раз Николас Закас запостил [свои мысли](https://www.nczonline.net/blog/2015/12/why-im-not-using-your-open-source-project/) о open-source проектах. Один из пунктов там, останавливающих его от использования таковых, является как раз отсутствие лицензии. Забавно просто)
