### ISSUE TITLE
X axis should start at 0

### ISSUE THREAD

**Issue by paulirish** [jsbench/jsbench.github.io#29]
We just ran a test evaluating var vs const, and the difference was 4300 ops/sec to 4320 ops/sec. 

However the chart made it feel like there was a massive difference in the two. 

Can the x axis start at 0 for better comparison of the results?

**Comment by RubaXa** [comment]
Yes, of course (+ option for switching to detailed view).

**Comment by RubaXa** [comment]
Done: https://dl.dropboxusercontent.com/s/xcffhe0nkwzyaoj/Screenshot%202016-05-19%2022.49.55.png?dl=0

**Comment by paulirish** [comment]
Excellent. thank you! @caseq
