### ISSUE TITLE
order of tests makes a lot of differnce

### ISSUE THREAD

**Issue by zba** [jsbench/jsbench.github.io#39]
I tried 4 simple tests:
`17*3, 3*17, 51/3, 51/17 `

which run first wins.
![image](https://user-images.githubusercontent.com/807956/159867629-389d6d56-3a6a-40dc-b2f2-3c183dab5dc9.png)
![image](https://user-images.githubusercontent.com/807956/159867789-2ce336a2-ac44-4faa-b2e1-fdb12d6d0e50.png)

**Comment by vanowm** [comment]
I'm unable reproduce this on Edge 126
All 4 tests are so close to each other within margin of error, that they fluctuate on every run.
![image](https://github.com/jsbench/jsbench.github.io/assets/511517/acd9ef8f-a41f-40d1-8f80-c01b56c3498f)

![image](https://github.com/jsbench/jsbench.github.io/assets/511517/9b1503fb-6822-45d4-82da-c80c1595946b)

Most of the time I'm getting something like this:
![image](https://github.com/jsbench/jsbench.github.io/assets/511517/c4e11aa9-80c9-4a44-b9c4-55ad3a7e4259)

**Comment by zba** [comment]
it was 2 years ago, probably fixed,
