### ISSUE TITLE
Перенести сборку в `/bundles/`

### ISSUE THREAD

**Issue by RubaXa** [jsbench/jsbench.github.io#8]
Всё же надо сделать папку `/bundles/` в которую будут складываться собранные js и css, да и другой хлам.

Это нужно затем, чтобы в редакторе (например WebStorm) можно было исключить эту папку, то сейчас моя IDE индексирует этот файл :[

**Comment by nicksp** [comment]
И индекс.html туда же? Чтобы веб сервер стартовал оттуда и там был полностью рабочий проект?

**Comment by RubaXa** [comment]
Не, index.html должен лежать в корне, сервера же нет, github только статику отдает, ему невозможно объяснить откуда брать html

**Comment by nicksp** [comment]
А для локального веб-сервера как поступить, который из галп стартует?
Натравить его на корень, а в index.html ссылки сделать на скомпиленные файлы из `bundle` директории?

**Comment by RubaXa** [comment]
Ну да, ровно тоже самое что и сейчас, только `src/jsbench.bundle.js` -> `bundles/jsbench.js`

**Comment by nicksp** [comment]
Сегодня сделаю этот пункт. Но пока будет, видимо, один jsbench.js файл. CSS когда вырастет, тоже туда поместим скомпиленный из sass
